libraries:
  Comedy:
    collection_files:
    - file: config/collections/comedy/comedians.yaml
      asset_directory: C:\Users\Derek\Library\images\Collections\people
    - file: config/collections/comedy/comedy.yaml
      asset_directory: C:\Users\Derek\Library\images\Collections\comedy

    metadata_files: C:\Users\Derek\Library\metadata\comedy.yaml
    report_path: config/reports/comedy_report.yaml
    settings:
      asset_directory: C:\Users\Derek\Library\images\comedy

    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
      mass_genre_update: Stand-Up Comedy
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic
      content_rating_mapper: {'Not Rated': NR}
      mass_poster_update: tmdb
      mass_background_update: tmdb

  Test Movies:
    collection_files:
    - {template_variables: {section: '01'}, asset_directory: C:\Users\Derek\Library\images\collections\basic, file: config/collections/basic/movies.yaml}
    - {template_variables: {section: '01'}, asset_directory: C:\Users\Derek\Library\images\collections\basic, file: config/collections/basic/both.yaml}
    - {template_variables: {section: '02'}, asset_directory: C:\Users\Derek\Library\images\collections\seasonal, file: config/collections/seasonal/movies.yaml}
    - {template_variables: {section: '03'}, asset_directory: C:\Users\Derek\Library\images\collections\charts, file: config/collections/charts/movies.yaml}
    - {template_variables: {section: '03'}, asset_directory: C:\Users\Derek\Library\images\collections\charts, file: config/collections/charts/both.yaml}
    - {template_variables: {section: '04'}, asset_directory: C:\Users\Derek\Library\images\collections\series, file: config/collections/series/movies.yaml}
    - {template_variables: {section: '04'}, asset_directory: C:\Users\Derek\Library\images\collections\series, file: config/collections/series/both.yaml}
    - {template_variables: {section: '05'}, asset_directory: C:\Users\Derek\Library\images\collections\decades, file: config/collections/decades/decades.yaml}
    - {template_variables: {section: '06'}, asset_directory: C:\Users\Derek\Library\images\collections\genres, file: config/collections/genres/movies.yaml}
    - {template_variables: {section: '06'}, asset_directory: C:\Users\Derek\Library\images\collections\genres, file: config/collections/genres/both.yaml}
    - {template_variables: {section: '07'}, asset_directory: C:\Users\Derek\Library\images\collections\studios, file: config/collections/studios/studios.yaml}
    - {template_variables: {section: '08'}, asset_directory: C:\Users\Derek\Library\images\collections\formats, file: config/collections/formats/movies.yaml}
    - {template_variables: {section: '08'}, asset_directory: C:\Users\Derek\Library\images\collections\formats, file: config/collections/formats/both.yaml}
    - {template_variables: {section: '09'}, asset_directory: C:\Users\Derek\Library\images\collections\people, file: config/collections/people/movies.yaml}
    - {template_variables: {section: '09'}, asset_directory: C:\Users\Derek\Library\images\collections\people, file: config/collections/people/both.yaml}

    metadata_files: C:\Users\Derek\Library\metadata\Movies.yaml
    overlay_files:
    - file: config/overlays/movies.yaml
    - file: config/overlays/both.yaml

    report_path: config/reports/movies_report.yaml
    settings:
      asset_directory: C:\Users\Derek\Library\images\Movies

    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
      mass_genre_update: reset
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic
      content_rating_mapper: {'Not Rated': NR}

  Shows:
    collection_files:
    - {template_variables: {section: '01'}, asset_directory: C:\Users\Derek\Library\images\collections\basic, file: config/collections/basic/shows.yaml}
    - {template_variables: {section: '01'}, asset_directory: C:\Users\Derek\Library\images\collections\basic, file: config/collections/basic/both.yaml}
    - {template_variables: {section: '02'}, asset_directory: C:\Users\Derek\Library\images\collections\seasonal, file: config/collections/seasonal/shows.yaml}
    - {template_variables: {section: '03'}, asset_directory: C:\Users\Derek\Library\images\collections\charts, file: config/collections/charts/shows.yaml}
    - {template_variables: {section: '03'}, asset_directory: C:\Users\Derek\Library\images\collections\charts, file: config/collections/charts/both.yaml}
    - {template_variables: {section: '04'}, asset_directory: C:\Users\Derek\Library\images\collections\series, file: config/collections/series/shows.yaml}
    - {template_variables: {section: '04'}, asset_directory: C:\Users\Derek\Library\images\collections\series, file: config/collections/series/both.yaml}
    - {template_variables: {section: '05'}, asset_directory: C:\Users\Derek\Library\images\collections\decades, file: config/collections/decades/decades.yaml}
    - {template_variables: {section: '06'}, asset_directory: C:\Users\Derek\Library\images\collections\genres, file: config/collections/genres/shows.yaml}
    - {template_variables: {section: '06'}, asset_directory: C:\Users\Derek\Library\images\collections\genres, file: config/collections/genres/both.yaml}
    - {template_variables: {section: '07'}, asset_directory: C:\Users\Derek\Library\images\collections\networks, file: config/collections/networks/networks.yaml}
    - {template_variables: {section: '08'}, asset_directory: C:\Users\Derek\Library\images\collections\formats, file: config/collections/formats/shows.yaml}
    - {template_variables: {section: '08'}, asset_directory: C:\Users\Derek\Library\images\collections\formats, file: config/collections/formats/both.yaml}
    - {template_variables: {section: '09'}, asset_directory: C:\Users\Derek\Library\images\collections\people, file: config/collections/people/shows.yaml}
    - {template_variables: {section: '09'}, asset_directory: C:\Users\Derek\Library\images\collections\people, file: config/collections/people/both.yaml}

    metadata_files: C:\Users\Derek\Library\metadata\Shows.yaml
    overlay_files:
    - {file: config/overlays/shows.yaml}
    - {file: config/overlays/both.yaml}
    - {file: config/overlays/both.yaml, template_variables: {level: season}}
    - {file: config/overlays/both.yaml, template_variables: {level: episode}}

    report_path: config/reports/shows_report.yaml
    settings:
      asset_directory: C:\Users\Derek\Library\images\Shows

    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
      mass_genre_update: reset
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_episode_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic
      content_rating_mapper: {'Not Rated': NR}

playlist_files:
  file: config/playlists/playlists.yaml
  asset_directory: C:\Users\Derek\Library\images\playlists
  template_variables:
    libraries: [Movies, Shows]

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays

  # Cache
  cache: true
  cache_expiration: 60

  # Assets
  asset_directory:
  asset_folders: true
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: true
  download_url_assets: false
  show_asset_not_needed: false
  show_missing_season_assets: true
  show_missing_episode_assets: true

  # Collections
  sync_mode: sync
  minimum_items: 1
  default_collection_order: alpha
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true

  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false

  save_report: true
  tvdb_language: eng
  playlist_sync_to_users: all
  playlist_report: false
  verify_ssl: true

  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 95
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_exclude_users:
  custom_repo:

webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

plex:
  url: http://127.0.0.1:32400/
  token: ################################
  timeout: 60
  db_cache: 512
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:

tmdb:
  apikey: ################################
  language: en
  cache_expiration: 60
  region:

# tautulli:
#   url: http://127.0.0.1:8181
#   #url: ################################
#   apikey: ################################

trakt:
  client_id: ################################
  client_secret: ################################
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

mdblist:
  apikey: ################################
  cache_expiration: 60
omdb:
  apikey: de26f375
  cache_expiration: 60

# notifiarr:
#   apikey: ####################################
# github:
#   token: ################################
# gotify:
#   url: http://192.168.1.12:80
#   token: ####################################

# radarr:
#   url: #http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/Movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   ignore_cache: false

# sonarr:
#   url: #http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/TV Shows
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
#   ignore_cache: false
