libraries:
  Movies:
    collection_files:
    - file: collections/common.yaml
      asset_directory: /images/collections
    - file: collections/movies.yaml
      asset_directory: /images/collections

    metadata_files: /metadata/movies.yaml
    overlay_files:
    - file: overlays.yaml
    settings:
      asset_directory: /images/movies

    operations:
      assets_for_all: true
      mass_originally_available_update: tmdb
      # Genres
      mass_genre_update: imdb
      # mass_genre_update: reset
      genre_mapper:
        "Film-Noir": ""
        "Sci-Fi": Science Fiction
        "Sport": Sports
      # Ratings
      mass_audience_rating_update: imdb
      mass_critic_rating_update: [trakt_user, mdb_metacritic]
      mass_user_rating_update: trakt_user
      # Images
      mass_poster_update: tmdb
      mass_background_update: tmdb

  Shows:
    collection_files:
    - file: collections/common.yaml
      asset_directory: /images/collections
    - file: collections/shows.yaml
      asset_directory: /images/collections

    metadata_files: /metadata/shows.yaml
    overlay_files:
    - file: overlays.yaml
    settings:
      asset_directory: /images/shows

    operations:
      assets_for_all: true
      mass_originally_available_update: tmdb
      # Genres
      mass_genre_update: [tvdb, tmdb]
      # mass_genre_update: reset
      genre_mapper:
        "Children": Family
        "Game-Show": Game Show
        "Martial Arts": ""
        "Mini-Series": Miniseries
        "Reality-TV": Reality
        "Sci-Fi": Science Fiction
        "Sport": Sports
        "Talk-Show": Talk Show
      # Ratings
      mass_audience_rating_update: imdb
      mass_episode_audience_rating_update: imdb
      mass_critic_rating_update: [trakt_user, mdb_metacritic]
      mass_user_rating_update: trakt_user
      # Images
      mass_poster_update:
        source: tmdb
        seasons: true
        episodes: true
      mass_background_update:
        source: tmdb
        seasons: true
        episodes: true

playlist_files:
- file: playlists.yaml
  asset_directory: /images/playlists

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays

  # Cache
  cache: true
  cache_expiration: 60

  # Assets
  asset_directory: assets
  asset_folders: true
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_season_assets: true
  show_missing_episode_assets: true
  show_asset_not_needed: false

  sync_mode: sync
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true

  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false

  save_report: true
  report_path: report/missing_report.yaml
  tvdb_language: eng
  playlist_sync_to_users: all
  playlist_report: true
  verify_ssl: true

  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 95
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_exclude_users:
  custom_repo:

webhooks: # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

plex: # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://127.0.0.1:32400/
  token: ################################
  timeout: 60
  db_cache: 512
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:

tmdb: # REQUIRED for the script to run
  apikey: ################################
  language: en
  cache_expiration: 60
  region:
# tautulli: # Can be individually specified per library as well
#   url: http://127.0.0.1:8181
#   #url: http://192.168.50.82:8181/127.0.0.1
#   apikey: ################################-u

trakt:
  client_id: ################################
  client_secret: ################################
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

mdblist:
  apikey: ################################
  cache_expiration: 60

omdb:
  apikey: de26f375
  cache_expiration: 60

# radarr: # Can be individually specified per library as well
#   url: #http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/Movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   ignore_cache: false

# sonarr: # Can be individually specified per library as well
#   url: #http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/TV Shows
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
#   ignore_cache: false

# notifiarr:
#   apikey: ####################################
# github:
#   token: ################################
# gotify:
#   url: http://192.168.1.12:80
#   token: ####################################
