libraries:
  Comedy:
    collection_files:
    - {asset_directory: /images/collections/comedy, file: /kometa/collections/comedy/comedy.yaml}
    - {asset_directory: /images/collections/people, file: /kometa/collections/comedy/comedians.yaml}

    metadata_files: /metadata/comedy.yaml
    report_path: /kometa/reports/comedy_report.yaml
    settings:
      asset_directory: /images/comedy

    operations:
      assets_for_all: true
      delete_collections: {configured: false, managed: true}
      mass_genre_update: Stand-Up Comedy
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic
      content_rating_mapper: {'Not Rated': NR}

  Movies:
    collection_files:
    - {file: /kometa/collections/prerolls.yaml, schedule: weekly(monday)}

    # - {file: /kometa/labels/reset.yaml}
    # - {file: /kometa/labels/audio/audio.yaml}
    # - {file: /kometa/labels/editions/editions.yaml}
    # - {file: /kometa/labels/favorites/movies.yaml}
    # - {file: /kometa/labels/favorites/both.yaml}
    # - {file: /kometa/labels/genres/movies.yaml}
    # - {file: /kometa/labels/genres/both.yaml}
    # - {file: /kometa/labels/source/sources.yaml}
    # - {file: /kometa/labels/tags/tags.yaml}

    - {template_variables: {section: '01'}, asset_directory: /images/collections/basic, file: /kometa/collections/basic/movies.yaml}
    - {template_variables: {section: '01'}, asset_directory: /images/collections/basic, file: /kometa/collections/basic/both.yaml}
    - {template_variables: {section: '02'}, asset_directory: /images/collections/seasonal, file: /kometa/collections/seasonal/movies.yaml}
    - {template_variables: {section: '02'}, asset_directory: /images/collections/seasonal, file: /kometa/collections/seasonal/both.yaml}
    - {template_variables: {section: '03'}, asset_directory: /images/collections/charts, file: /kometa/collections/charts/movies.yaml}
    - {template_variables: {section: '03'}, asset_directory: /images/collections/charts, file: /kometa/collections/charts/both.yaml}
    - {template_variables: {section: '04'}, asset_directory: /images/collections/series, file: /kometa/collections/series/movies.yaml}
    - {template_variables: {section: '04'}, asset_directory: /images/collections/series, file: /kometa/collections/series/both.yaml}
    - {template_variables: {section: '05'}, asset_directory: /images/collections/decades, file: /kometa/collections/decades/decades.yaml}
    - {template_variables: {section: '06'}, asset_directory: /images/collections/genres, file: /kometa/collections/genres/movies.yaml}
    - {template_variables: {section: '06'}, asset_directory: /images/collections/genres, file: /kometa/collections/genres/both.yaml}
    - {template_variables: {section: '07'}, asset_directory: /images/collections/studios, file: /kometa/collections/studios/studios.yaml}
    - {template_variables: {section: '08'}, asset_directory: /images/collections/formats, file: /kometa/collections/formats/movies.yaml}
    - {template_variables: {section: '08'}, asset_directory: /images/collections/formats, file: /kometa/collections/formats/both.yaml}
    - {template_variables: {section: '09'}, asset_directory: /images/collections/people, file: /kometa/collections/people/movies.yaml}
    - {template_variables: {section: '09'}, asset_directory: /images/collections/people, file: /kometa/collections/people/both.yaml}
    - {asset_directory: /images/collections, file: /kometa/collections/collectionless.yaml}

    metadata_files: /metadata/movies.yaml
    overlay_files:
    - file: /kometa/overlays/movies.yaml
    - file: /kometa/overlays/both.yaml

    report_path: /kometa/reports/movies_report.yaml
    settings:
      asset_directory: /images/movies

    operations:
      assets_for_all: true
      delete_collections: {configured: false, managed: true}
      mass_genre_update: reset
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic

  Shows:
    collection_files:
    # - {file: /kometa/labels/reset.yaml}
    # - {file: /kometa/labels/audio/audio.yaml}
    # - {file: /kometa/labels/editions/editions.yaml}
    # - {file: /kometa/labels/favorites/shows.yaml}
    # - {file: /kometa/labels/favorites/both.yaml}
    # - {file: /kometa/labels/genres/shows.yaml}
    # - {file: /kometa/labels/genres/both.yaml}
    # - {file: /kometa/labels/source/sources.yaml}
    # - {file: /kometa/labels/tags/tags.yaml}

    - {template_variables: {section: '01'}, asset_directory: /images/collections/basic, file: /kometa/collections/basic/shows.yaml}
    - {template_variables: {section: '01'}, asset_directory: /images/collections/basic, file: /kometa/collections/basic/both.yaml}
    - {template_variables: {section: '02'}, asset_directory: /images/collections/seasonal, file: /kometa/collections/seasonal/shows.yaml}
    - {template_variables: {section: '02'}, asset_directory: /images/collections/seasonal, file: /kometa/collections/seasonal/both.yaml}
    - {template_variables: {section: '03'}, asset_directory: /images/collections/charts, file: /kometa/collections/charts/shows.yaml}
    - {template_variables: {section: '03'}, asset_directory: /images/collections/charts, file: /kometa/collections/charts/both.yaml}
    - {template_variables: {section: '04'}, asset_directory: /images/collections/series, file: /kometa/collections/series/shows.yaml}
    - {template_variables: {section: '04'}, asset_directory: /images/collections/series, file: /kometa/collections/series/both.yaml}
    - {template_variables: {section: '05'}, asset_directory: /images/collections/decades, file: /kometa/collections/decades/decades.yaml}
    - {template_variables: {section: '06'}, asset_directory: /images/collections/genres, file: /kometa/collections/genres/shows.yaml}
    - {template_variables: {section: '06'}, asset_directory: /images/collections/genres, file: /kometa/collections/genres/both.yaml}
    - {template_variables: {section: '07'}, asset_directory: /images/collections/networks, file: /kometa/collections/networks/networks.yaml}
    - {template_variables: {section: '08'}, asset_directory: /images/collections/formats, file: /kometa/collections/formats/shows.yaml}
    - {template_variables: {section: '08'}, asset_directory: /images/collections/formats, file: /kometa/collections/formats/both.yaml}
    - {template_variables: {section: '09'}, asset_directory: /images/collections/people, file: /kometa/collections/people/shows.yaml}
    - {template_variables: {section: '09'}, asset_directory: /images/collections/people, file: /kometa/collections/people/both.yaml}
    - {asset_directory: /images/collections, file: /kometa/collections/collectionless.yaml}

    metadata_files: /metadata/shows.yaml
    overlay_files:
    - {file: /kometa/overlays/shows.yaml}
    - {file: /kometa/overlays/both.yaml}
    - {file: /kometa/overlays/both.yaml, template_variables: {level: season}}
    - {file: /kometa/overlays/both.yaml, template_variables: {level: episode}}

    report_path: /kometa/reports/shows_report.yaml
    settings:
      asset_directory: /images/shows

    operations:
      assets_for_all: true
      delete_collections: {configured: false, managed: true}
      mass_genre_update: reset
      mass_studio_update: tmdb
      mass_originally_available_update: tmdb
      mass_audience_rating_update: [imdb, tmdb]
      mass_episode_audience_rating_update: [imdb, tmdb]
      mass_critic_rating_update: mdb_metacritic

playlist_files:
  file: /kometa/playlists/playlists.yaml
  asset_directory: /images/playlists
  template_variables:
    libraries: [Movies, Shows]

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays

  # Cache
  cache: true
  cache_expiration: 60

  # Assets
  asset_directory:
  asset_depth: 2
  asset_folders: true
  create_asset_folders: true
  dimensional_asset_rename: true
  download_url_assets: false
  prioritize_assets: true
  show_asset_not_needed: false
  show_missing_season_assets: true
  show_missing_episode_assets: true

  # Collections
  sync_mode: sync
  minimum_items: 1
  default_collection_order: alpha
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true

  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false

  save_report: true
  tvdb_language: eng

  # Playlists
  playlist_exclude_users:
  playlist_sync_to_users: all
  playlist_report: false

  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 95
  custom_repo:

  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  verify_ssl: true

webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

plex:
  url: http://127.0.0.1:32400/
  token: ################################
  timeout: 60
  db_cache: 512
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:

tmdb:
  apikey: ################################
  language: en
  cache_expiration: 60
  region:

# tautulli:
#   url: http://127.0.0.1:8181
#   #url: ################################
#   apikey: ################################

trakt:
  client_id: ################################
  client_secret: ################################
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

mdblist:
  apikey: ################################
  cache_expiration: 60
omdb:
  apikey: ########
  cache_expiration: 60

# notifiarr:
#   apikey: ####################################
# github:
#   token: ################################
# gotify:
#   url: http://192.168.1.12:80
#   token: ####################################

# radarr:
#   url: #http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/Movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   ignore_cache: false

# sonarr:
#   url: #http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: S:/TV Shows
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
#   ignore_cache: false
