version: "3.2"
services:
  kometa:
    image: kometateam/kometa
    container_name: kometa
    environment:
      - TZ=TIMEZONE #optional
      - KOMETA_CONFIG=/media-library/kometa/config.yaml
      - KOMETA_TIMES=06:00
    volumes:
      - /mnt/user/appdata/kometa/config:/config:rw
      - /mnt/user/media-library:/library
    restart: unless-stopped
