templates:
  chart:
    default:
      section: '00'
      sort_prefix: '>'
      sort: <<collection_sort>>
    sort_title: '!<<section>>-Charts-<<sort_prefix>> <<sort>>'
    label: Charts
    collection_order: custom
    collection_mode: hide
    visible_library: true
    visible_home: true
    visible_shared: true
    # content_rating: ''
